'use client';
import {useEffect,useState} from 'react';
import {adminRepository} from '../../../lib/data/admin-repository';
import type {AdminSection,OrderStatus} from '../../../lib/domain/types';
const sections=new Set<AdminSection>(['products','categories','inventory','orders','customers','banners','featured','settings']);
const statuses:OrderStatus[]=['pending','confirmed','preparing','out_for_delivery','delivered','cancelled'];
export default function Section({params}:{params:Promise<{section:string}>}){
 const [section,setSection]=useState<AdminSection|null>(null),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<any|null>(null);
 useEffect(()=>{params.then(({section:v})=>setSection(v as AdminSection))},[params]);
 useEffect(()=>{if(section&&sections.has(section))load()},[section]);
 async function load(){setLoading(true);setError('');try{setRows(await adminRepository.list(section!))}catch(e:any){setError(e.message??'Unable to load data')}finally{setLoading(false)}}
 async function remove(id:string){if(!confirm('Delete this record permanently?'))return;try{await adminRepository.remove(section==='inventory'?'products':section!,id);load()}catch(e:any){setError(e.message)}}
 async function updateStatus(id:string,status:OrderStatus){try{await adminRepository.setOrderStatus(id,status);load()}catch(e:any){setError(e.message)}}
 if(!section)return <main className="p-10">Loading…</main>; if(!sections.has(section))return <main className="p-10">Unknown section</main>;
 const editable=['products','categories','banners','featured'].includes(section);
 return <main className="min-h-screen p-5 md:p-10"><div className="mb-8 flex items-center justify-between"><div><a href="/dashboard" className="text-sm text-leaf-700">← Dashboard</a><h1 className="mt-2 text-3xl font-black capitalize">{section}</h1></div>{editable&&<button onClick={()=>setEditing({})} className="rounded-xl bg-leaf-700 px-4 py-3 font-bold text-white">Add new</button>}</div>{error&&<div className="mb-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}<div className="glass overflow-x-auto rounded-3xl p-5">{loading?<p className="animate-pulse text-slate-500">Loading records…</p>:rows.length===0?<div className="py-12 text-center text-slate-500">No records found yet.</div>:<table className="w-full text-left"><thead><tr className="border-b border-leaf-50 text-sm text-slate-500"><th className="p-3">Name</th><th className="p-3">Status / value</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i} className="border-b border-leaf-50"><td className="p-3 font-semibold">{r.name_en??r.full_name??r.email??r.id}</td><td className="p-3">{section==='orders'?<select value={r.status} onChange={e=>updateStatus(r.id,e.target.value as OrderStatus)} className="rounded-lg border p-2">{statuses.map(s=><option key={s} value={s}>{s}</option>)}</select>:String(r.price_iqd??r.stock??r.is_active??'—')}</td><td className="p-3">{editable&&<><button onClick={()=>setEditing(r)} className="mr-2 rounded-lg bg-leaf-50 px-3 py-2 text-leaf-700">Edit</button><button onClick={()=>remove(r.id)} className="rounded-lg bg-red-50 px-3 py-2 text-red-600">Delete</button></>}</td></tr>)}</tbody></table>}</div>{editing&&<Editor section={section} row={editing} close={()=>setEditing(null)} saved={()=>{setEditing(null);load()}}/>}</main>
}
function Editor({section,row,close,saved}:{section:AdminSection;row:any;close:()=>void;saved:()=>void}){const[form,setForm]=useState({...row});const[file,setFile]=useState<File|null>(null);const[busy,setBusy]=useState(false);const set=(k:string,v:unknown)=>setForm({...form,[k]:v});async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{let image=form.image_url??'';if(file)image=await adminRepository.upload(file);const values=section==='products'?{name_ku:form.name_ku??'',name_ar:form.name_ar??'',name_en:form.name_en??'',description:form.description??'',price_iqd:Number(form.price_iqd??0),price_per_unit:Number(form.price_iqd??0),original_price:Number(form.price_iqd??0),stock:Number(form.stock??0),unit_type:form.unit_type??'kg',unit_label:form.unit_label??form.unit_type??'kg',is_active:form.is_active!==false,image_url:image}:{name_ku:form.name_ku??'',name_ar:form.name_ar??'',name_en:form.name_en??'',image};await adminRepository.save(section,values,form.id);saved()}catch(e:any){alert(e.message??'Save failed')}finally{setBusy(false)}}return <div className="fixed inset-0 grid place-items-center bg-black/30 p-5"><form onSubmit={submit} className="glass max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl p-7"><h2 className="text-2xl font-black">{form.id?'Edit':'Add'} {section}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{['name_ku','name_ar','name_en'].map(k=><input required key={k} placeholder={k} value={form[k]??''} onChange={e=>set(k,e.target.value)} className="rounded-xl border p-3"/>)}{section==='products'&&<><input type="number" min="0" required placeholder="Price IQD" value={form.price_iqd??''} onChange={e=>set('price_iqd',e.target.value)} className="rounded-xl border p-3"/><input type="number" min="0" required placeholder="Stock" value={form.stock??''} onChange={e=>set('stock',e.target.value)} className="rounded-xl border p-3"/><select value={form.unit_type??'kg'} onChange={e=>set('unit_type',e.target.value)} className="rounded-xl border p-3"><option value="kg">Kg</option><option value="g">Gram</option><option value="bag">Bag</option></select><input placeholder="Description" value={form.description??''} onChange={e=>set('description',e.target.value)} className="rounded-xl border p-3 sm:col-span-2"/></>}</div><input className="mt-4" type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl border px-4 py-3">Cancel</button><button disabled={busy} className="rounded-xl bg-leaf-700 px-5 py-3 font-bold text-white">{busy?'Saving…':'Save'}</button></div></form></div>}
