'use client';

import {Check,ChevronLeft,ChevronRight,Eye,ImagePlus,Loader2,Pencil,Plus,RefreshCw,Search,Trash2,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {adminRepository} from '../lib/data/admin-repository';
import type {AdminField,AdminSection,FieldOption,OrderStatus,SectionConfig,UserRole} from '../lib/domain/types';

const statuses:OrderStatus[]=['pending','confirmed','preparing','ready_for_pickup','out_for_delivery','delivered','cancelled'];
const roles:UserRole[]=['customer','store_owner','driver','admin'];
const readable=(value:unknown)=>value===true?'Yes':value===false?'No':value==null||value===''?'—':typeof value==='object'?JSON.stringify(value):String(value);

export function DataSection({section,config}:{section:AdminSection;config:SectionConfig}){
  const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<any|null>(null),[viewing,setViewing]=useState<any|null>(null);
  const size=12;
  async function load(){setLoading(true);setError('');try{setRows(await adminRepository.list(section))}catch(e:any){setError(e.message??'Unable to load records')}finally{setLoading(false)}}
  useEffect(()=>{load()},[section]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(row=>config.searchKeys.some(key=>readable(row[key]).toLowerCase().includes(q))):rows},[rows,query,config.searchKeys]);
  const pages=Math.max(1,Math.ceil(filtered.length/size)),shown=filtered.slice((page-1)*size,page*size);
  useEffect(()=>setPage(1),[query,section]);
  async function remove(row:any){const id=row[config.primaryKey??(section==='drivers'?'user_id':section==='content'?'key':'id')];if(!confirm(section==='customers'?'Permanently delete this account and its linked data? This cannot be undone.':'Delete this record permanently?'))return;try{await adminRepository.remove(section,id);setNotice('Record deleted successfully.');await load()}catch(e:any){setError(e.message??'Delete failed')}}
  async function status(id:string,value:OrderStatus){try{await adminRepository.setOrderStatus(id,value);setNotice('Order status updated.');await load()}catch(e:any){setError(e.message)}}
  async function role(id:string,value:UserRole,enabled:boolean){if(!confirm(`${enabled?'Grant':'Remove'} ${value.replaceAll('_',' ')} access?`))return;try{await adminRepository.setUserRole(id,value,enabled);setNotice('Account permissions updated.');await load()}catch(e:any){setError(e.message)}}
  return <>
    <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-leaf-700">Mini group operations</p><h1 className="mt-1 text-3xl font-black tracking-tight">{config.title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{config.description}</p></div>{config.canCreate&&<button onClick={()=>setEditing({})} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-leaf-700 px-5 py-3 font-bold text-white shadow-lg hover:bg-leaf-800"><Plus className="h-5 w-5"/>Add new</button>}</header>
    {(error||notice)&&<div role="alert" className={`mb-5 flex justify-between rounded-2xl border p-4 text-sm ${error?'border-red-100 bg-red-50 text-red-700':'border-leaf-100 bg-leaf-50 text-leaf-800'}`}><span>{error||notice}</span><button onClick={()=>{setError('');setNotice('')}}><X className="h-4 w-4"/></button></div>}
    <section className="glass rounded-[28px] p-4 sm:p-6"><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="field pl-12" placeholder={`Search ${config.title.toLowerCase()}…`}/></label><button onClick={load} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-leaf-100 bg-white px-4 py-3 text-sm font-bold text-leaf-800"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button><span className="rounded-xl bg-leaf-50 px-3 py-3 text-center text-xs font-bold text-leaf-800">{filtered.length} records</span></div>
      <div className="scrollbar overflow-x-auto">{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-leaf-700"/></div>:shown.length===0?<div className="grid min-h-64 place-items-center text-center"><div><Search className="mx-auto text-leaf-700"/><p className="mt-4 font-bold">No records found</p></div></div>:<table className="w-full min-w-[760px] text-left"><thead><tr className="border-b text-xs font-black uppercase tracking-wider text-slate-400">{config.columns.map(c=><th className="px-3 py-4" key={c.key}>{c.label}</th>)}<th className="px-3 py-4 text-right">Actions</th></tr></thead><tbody>{shown.map((row,index)=><tr key={row[config.primaryKey??'id']??index} className="border-b border-slate-100 text-sm last:border-0 hover:bg-white/60">{config.columns.map(c=><td className="max-w-[280px] truncate px-3 py-4" key={c.key}>{section==='orders'&&c.key==='status'?<select value={row.status} onChange={e=>status(row.id,e.target.value as OrderStatus)} className="rounded-xl border bg-white px-3 py-2 font-semibold">{statuses.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select>:section==='customers'&&c.key==='role'?<RoleControl row={row} change={role}/>:c.key.includes('image')&&row[c.key]?<img alt="" src={row[c.key]} className="h-12 w-16 rounded-xl object-cover"/>:<span className={c.key==='is_active'?(row[c.key]?'font-bold text-leaf-700':'font-bold text-red-500'):''}>{readable(row[c.key])}</span>}</td>)}<td className="px-3 py-4"><div className="flex justify-end gap-2"><button title="View details" onClick={()=>setViewing(row)} className="rounded-xl bg-blue-50 p-2.5 text-blue-700"><Eye className="h-4 w-4"/></button>{config.canEdit&&<button title="Edit" onClick={()=>setEditing(row)} className="rounded-xl bg-leaf-50 p-2.5 text-leaf-700"><Pencil className="h-4 w-4"/></button>}{config.canDelete&&<button title="Delete" onClick={()=>remove(row)} className="rounded-xl bg-red-50 p-2.5 text-red-600"><Trash2 className="h-4 w-4"/></button>}</div></td></tr>)}</tbody></table>}</div>
      {pages>1&&<div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-sm text-slate-500">Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(x=>x-1)} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronLeft/></button><button disabled={page===pages} onClick={()=>setPage(x=>x+1)} className="rounded-xl border bg-white p-2 disabled:opacity-40"><ChevronRight/></button></div></div>}
    </section>
    {editing!==null&&<Editor section={section} config={config} row={editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);setNotice('Changes saved successfully.');await load()}}/>}
    {viewing&&<RecordViewer title={`${config.title} details`} row={viewing} close={()=>setViewing(null)}/>} 
  </>;
}

function RoleControl({row,change}:{row:any;change:(id:string,role:UserRole,enabled:boolean)=>void}){const assigned=new Set<UserRole>((row.roles?.length?row.roles:[row.role??'customer']) as UserRole[]);return <div className="flex max-w-[320px] flex-wrap gap-1">{roles.map(role=><button key={role} onClick={()=>change(row.id,role,!assigned.has(role))} className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${assigned.has(role)?'bg-leaf-700 text-white':'bg-slate-100 text-slate-500'}`}>{assigned.has(role)&&<Check className="mr-1 inline h-3 w-3"/>}{role.replaceAll('_',' ')}</button>)}</div>}

function RecordViewer({title,row,close}:{title:string;row:any;close:()=>void}){return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/55 p-3 backdrop-blur-sm"><div className="scrollbar glass max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[30px] p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} className="rounded-xl bg-slate-100 p-2"><X/></button></div><dl className="mt-6 grid gap-3 sm:grid-cols-2">{Object.entries(row).filter(([key])=>key!=='roles').map(([key,value])=><div key={key} className="rounded-2xl bg-white/75 p-4"><dt className="text-xs font-black uppercase tracking-wider text-slate-400">{key.replaceAll('_',' ')}</dt><dd className="mt-2 break-words text-sm font-semibold">{readable(value)}</dd></div>)}</dl><button onClick={close} className="mt-6 w-full rounded-2xl bg-leaf-700 p-3 font-bold text-white">Close</button></div></div>}

function Editor({section,config,row,close,saved}:{section:AdminSection;config:SectionConfig;row:any;close:()=>void;saved:()=>void}){
  const initial={...row};
  if(!row.id&&!row.user_id){
    for(const field of config.fields){
      if(field.kind==='boolean')initial[field.key]=field.key==='is_available'?false:true;
      if(field.kind==='number'&&field.key==='sort_order')initial[field.key]=0;
    }
  }
  const [form,setForm]=useState<Record<string,any>>(initial),[files,setFiles]=useState<Record<string,File>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[options,setOptions]=useState<Record<string,FieldOption[]>>({});
  useEffect(()=>{adminRepository.options().then(setOptions).catch(()=>undefined)},[]);
  const set=(key:string,value:unknown)=>setForm(old=>({...old,[key]:value}));
  function choices(field:AdminField){if(field.options)return field.options;if(['owner_id','user_id'].includes(field.key))return options.users??[];if(['store_id','target_store_id'].includes(field.key))return options.stores??[];if(field.key==='category_id')return options.categories??[];if(field.key==='product_id')return options.products??[];return []}
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const values:Record<string,unknown>={};for(const field of config.fields){let value=form[field.key];if(files[field.key])value=await adminRepository.upload(files[field.key],section);if(field.kind==='image'){if(field.required&&!value)throw new Error(`${field.label} is required.`);if(value)values[field.key]=value;continue}if(field.kind==='number')value=value===''||value===undefined?null:Number(value);else if(field.kind==='json'&&typeof value==='string')value=value.trim()?JSON.parse(value):{};else if(field.kind==='datetime')value=value?new Date(value).toISOString():null;else if(field.kind==='boolean')value=Boolean(value);else if(['text','textarea'].includes(field.kind))value=value==null?'':String(value);else if(field.kind==='select'&&value==='')value=null;values[field.key]=value??(field.kind==='boolean'?false:null)}const id=row[config.primaryKey??(section==='drivers'?'user_id':section==='content'?'key':'id')];await adminRepository.save(section,values,id);await saved()}catch(e:any){setError(e.message??'Unable to save changes')}finally{setBusy(false)}}
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/55 p-3 backdrop-blur-sm"><form onSubmit={submit} className="scrollbar glass max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-[30px] p-5 sm:p-8"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-leaf-700">{row.id||row.user_id?'Edit record':'New record'}</p><h2 className="mt-1 text-2xl font-black">{config.title}</h2></div><button type="button" onClick={close} className="rounded-xl bg-slate-100 p-2"><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{config.fields.map(field=><Field key={field.key} field={field} value={form[field.key]} options={choices(field)} set={value=>set(field.key,value)} file={files[field.key]} setFile={file=>setFiles(old=>({...old,[field.key]:file}))}/>)}</div>{error&&<p className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mt-7 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-2xl border bg-white px-5 py-3 font-bold">Cancel</button><button disabled={busy} className="inline-flex items-center gap-2 rounded-2xl bg-leaf-700 px-6 py-3 font-bold text-white disabled:opacity-50">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}{busy?'Saving…':'Save changes'}</button></div></form></div>;
}

function Field({field,value,options,set,file,setFile}:{field:AdminField;value:any;options:FieldOption[];set:(v:any)=>void;file?:File;setFile:(f:File)=>void}){
  if(field.kind==='boolean')return <label className="flex items-center justify-between rounded-2xl border bg-white/80 p-4"><span className="font-semibold">{field.label}</span><input type="checkbox" className="h-5 w-5 accent-leaf-700" checked={value===true} onChange={e=>set(e.target.checked)}/></label>;
  if(field.kind==='image')return <label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">{field.label}{field.required&&' *'}</span><div className="flex items-center gap-4 rounded-2xl border border-dashed border-leaf-500 bg-leaf-50 p-4">{value?<img src={value} alt="Current" className="h-20 w-24 rounded-xl object-cover"/>:<div className="grid h-20 w-24 place-items-center rounded-xl bg-white text-leaf-700"><ImagePlus/></div>}<div><input required={field.required&&!value} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&setFile(e.target.files[0])}/><p className="mt-2 text-xs text-slate-500">{file?.name??'JPG, PNG or WebP · maximum 8 MB'}</p></div></div></label>;
  const common={required:field.required,readOnly:field.readOnly,placeholder:field.placeholder??field.label,className:'field',value:value??'',onChange:(e:any)=>set(e.target.value)};
  return <label className={['textarea','json'].includes(field.kind)?'sm:col-span-2':''}><span className="mb-2 block text-sm font-bold">{field.label}{field.required&&' *'}</span>{['textarea','json'].includes(field.kind)?<textarea {...common} rows={field.kind==='json'?5:3} value={field.kind==='json'&&typeof value==='object'?JSON.stringify(value,null,2):value??''}/>:field.kind==='select'?<select {...common}><option value="">Select {field.label.toLowerCase()}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input {...common} type={field.kind==='number'?'number':field.kind==='datetime'?'datetime-local':'text'} min={field.min} max={field.max} step={field.step}/>}</label>;
}
