import type {AdminSection,SectionConfig} from './domain/types';

const active={key:'is_active',label:'Active',kind:'boolean' as const};
const multilingual=[
  {key:'name_ku',label:'Badini name',kind:'text' as const,required:true},
  {key:'name_ar',label:'Arabic name',kind:'text' as const,required:true},
  {key:'name_en',label:'English name',kind:'text' as const,required:true},
];

export const sectionConfigs:Record<AdminSection,SectionConfig>={
  products:{title:'Products',description:'Catalogue, pricing, stock and availability',icon:'Package',table:'products',canCreate:true,canEdit:true,canDelete:true,searchKeys:['name_ku','name_ar','name_en','description'],columns:[{key:'name_en',label:'Product'},{key:'price_iqd',label:'Price IQD'},{key:'stock',label:'Stock'},{key:'is_active',label:'Active'}],fields:[...multilingual,{key:'description',label:'Description',kind:'textarea'},{key:'store_id',label:'Store',kind:'select',required:true},{key:'category_id',label:'Category',kind:'select',required:true},{key:'price_iqd',label:'Price IQD',kind:'number',required:true,min:0},{key:'stock',label:'Stock',kind:'number',required:true,min:0,step:.001},{key:'unit',label:'Unit',kind:'select',required:true,options:[{label:'Kilogram',value:'kg'},{label:'Gram',value:'g'},{label:'Bag',value:'bag'},{label:'Piece',value:'pcs'},{label:'Box / pack',value:'box'}]},{key:'image_url',label:'Product image',kind:'image'},active]},
  categories:{title:'Categories',description:'Multilingual catalogue groups and images',icon:'Tags',table:'categories',canCreate:true,canEdit:true,canDelete:true,searchKeys:['name_ku','name_ar','name_en'],columns:[{key:'name_en',label:'Category'},{key:'name_ku',label:'Badini'},{key:'is_active',label:'Active'}],fields:[...multilingual,{key:'image',label:'Category image',kind:'image'},active]},
  inventory:{title:'Inventory',description:'Stock levels, low-stock alerts and product availability',icon:'Warehouse',table:'products',canEdit:true,searchKeys:['name_ku','name_ar','name_en'],columns:[{key:'name_en',label:'Product'},{key:'stock',label:'Stock'},{key:'unit',label:'Unit'},{key:'is_active',label:'Available'}],fields:[{key:'stock',label:'Stock',kind:'number',required:true,min:0,step:.001},active]},
  orders:{title:'Orders',description:'Customer orders, payment totals and fulfilment status',icon:'ShoppingBag',table:'orders',searchKeys:['id','status','payment_method'],columns:[{key:'id',label:'Order'},{key:'status',label:'Status'},{key:'total_price',label:'Total IQD'},{key:'created_at',label:'Created'}],fields:[]},
  customers:{title:'Customers & roles',description:'Accounts, email addresses, profile state and access roles',icon:'Users',table:'users',canDelete:true,searchKeys:['full_name','first_name','last_name','username','email','phone'],columns:[{key:'full_name',label:'Customer'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'role',label:'Assigned roles'}],fields:[]},
  stores:{title:'Stores',description:'Vendor profiles, approval, delivery, pickup and map locations',icon:'Store',table:'stores',canCreate:true,canEdit:true,canDelete:true,searchKeys:['name','description','location','contact_phone'],columns:[{key:'name',label:'Store'},{key:'status',label:'Status'},{key:'location',label:'Location'},{key:'delivery_available',label:'Delivery'}],fields:[{key:'owner_id',label:'Owner account',kind:'select',required:true},{key:'name',label:'Store name',kind:'text',required:true},{key:'description',label:'Description',kind:'textarea'},{key:'location',label:'Address / area',kind:'text',required:true},{key:'contact_phone',label:'Phone',kind:'text'},{key:'latitude',label:'Latitude',kind:'number',step:.000001},{key:'longitude',label:'Longitude',kind:'number',step:.000001},{key:'delivery_radius_km',label:'Delivery radius (km)',kind:'number',min:.1,step:.1},{key:'opening_hours',label:'Opening hours JSON',kind:'json'},{key:'status',label:'Status',kind:'select',options:[{label:'Pending',value:'pending'},{label:'Active',value:'active'},{label:'Disabled',value:'disabled'}]},{key:'delivery_available',label:'Delivery enabled',kind:'boolean'},{key:'pickup_available',label:'Pickup enabled',kind:'boolean'},{key:'image',label:'Logo',kind:'image'},{key:'cover_image',label:'Cover image',kind:'image'}]},
  drivers:{title:'Delivery drivers',description:'Driver access, vehicles, availability and live coordinates',icon:'Truck',table:'drivers',primaryKey:'user_id',canCreate:true,canEdit:true,canDelete:true,searchKeys:['user_id','phone','vehicle_type','vehicle_plate'],columns:[{key:'user_id',label:'Account'},{key:'phone',label:'Phone'},{key:'vehicle_type',label:'Vehicle'},{key:'is_available',label:'Available'}],fields:[{key:'user_id',label:'Driver account',kind:'select',required:true},{key:'phone',label:'Phone',kind:'text'},{key:'vehicle_type',label:'Vehicle type',kind:'text'},{key:'vehicle_plate',label:'Vehicle plate',kind:'text'},{key:'is_available',label:'Available now',kind:'boolean'},active]},
  banners:{title:'Advertisement banners',description:'Image carousel, multilingual copy, links, stores and scheduling',icon:'Image',table:'banners',canCreate:true,canEdit:true,canDelete:true,searchKeys:['title_ku','title_ar','title_en','subtitle_ku','subtitle_ar','subtitle_en'],columns:[{key:'title_en',label:'Banner'},{key:'sort_order',label:'Order'},{key:'is_active',label:'Active'},{key:'starts_at',label:'Starts'}],fields:[{key:'title_ku',label:'Badini title',kind:'text',required:true},{key:'title_ar',label:'Arabic title',kind:'text',required:true},{key:'title_en',label:'English title',kind:'text',required:true},{key:'subtitle_ku',label:'Badini description',kind:'textarea'},{key:'subtitle_ar',label:'Arabic description',kind:'textarea'},{key:'subtitle_en',label:'English description',kind:'textarea'},{key:'cta_label_ku',label:'Badini button text',kind:'text'},{key:'cta_label_ar',label:'Arabic button text',kind:'text'},{key:'cta_label_en',label:'English button text',kind:'text'},{key:'target_store_id',label:'Linked store',kind:'select'},{key:'action_url',label:'External link',kind:'text',placeholder:'https://example.com'},{key:'sort_order',label:'Display order',kind:'number',min:0},{key:'starts_at',label:'Starts at',kind:'datetime'},{key:'ends_at',label:'Ends at',kind:'datetime'},{key:'image',label:'Banner image',kind:'image',required:true},active]},
  featured:{title:'Featured products',description:'Control products highlighted in customer discovery',icon:'Star',table:'featured_products',canCreate:true,canEdit:true,canDelete:true,searchKeys:['product_id'],columns:[{key:'product_id',label:'Product'},{key:'sort_order',label:'Order'},{key:'is_active',label:'Active'}],fields:[{key:'product_id',label:'Product',kind:'select',required:true},{key:'sort_order',label:'Display order',kind:'number',min:0},active]},
  content:{title:'App text & content',description:'Edit customer-facing copy independently in Badini, Arabic and English',icon:'Languages',table:'app_content',canCreate:true,canEdit:true,canDelete:true,searchKeys:['key','section','value_ku','value_ar','value_en'],columns:[{key:'key',label:'Content key'},{key:'section',label:'Section'},{key:'value_ku',label:'Badini'},{key:'is_active',label:'Active'}],fields:[{key:'key',label:'Unique key',kind:'text',required:true},{key:'section',label:'App section',kind:'select',required:true,options:['authentication','home','store','product','cart','checkout','orders','profile','settings','driver','store_owner','errors'].map(value=>({label:value.replace('_',' '),value}))},{key:'value_ku',label:'Badini text',kind:'textarea',required:true},{key:'value_ar',label:'Arabic text',kind:'textarea',required:true},{key:'value_en',label:'English text',kind:'textarea',required:true},{key:'description',label:'Internal note',kind:'textarea'},active]},
  settings:{title:'App settings',description:'Operational feature flags and application configuration',icon:'Settings',table:'app_settings',canCreate:true,canEdit:true,canDelete:true,searchKeys:['id'],columns:[{key:'id',label:'Setting'},{key:'value',label:'Value'},{key:'updated_at',label:'Updated'}],fields:[{key:'id',label:'Setting key',kind:'text',required:true},{key:'value',label:'JSON value',kind:'json',required:true}]},
  audit:{title:'Audit log',description:'Trace administrative changes and security-sensitive actions',icon:'ShieldCheck',table:'admin_audit_log',searchKeys:['action','entity','entity_id'],columns:[{key:'action',label:'Action'},{key:'entity',label:'Entity'},{key:'entity_id',label:'Record'},{key:'created_at',label:'Time'}],fields:[]},
};

export const adminSections=Object.entries(sectionConfigs) as [AdminSection,SectionConfig][];
