'use client';
import {FormEvent,useState} from 'react';
import {Eye,EyeOff,Leaf,Loader2,LockKeyhole,ShieldCheck} from 'lucide-react';

export default function Login(){
  const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/auth/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const data=await response.json();if(!response.ok)throw new Error(data.error??'Unable to sign in');location.replace('/dashboard')}catch(e:any){setError(e.message??'Unable to sign in')}finally{setBusy(false)}}
  return <main className="relative grid min-h-screen place-items-center overflow-hidden p-5"><div className="absolute -left-24 top-10 h-72 w-72 rounded-full bg-leaf-100/70 blur-3xl"/><div className="absolute -right-24 bottom-10 h-72 w-72 rounded-full bg-emerald-100/70 blur-3xl"/><form onSubmit={submit} className="glass relative w-full max-w-md rounded-[34px] p-7 sm:p-9"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-leaf-700 text-white"><Leaf/></div><div><div className="text-2xl font-black text-leaf-800">Mini group</div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Control Center</p></div></div><div className="mt-9 flex items-start gap-3 rounded-2xl bg-leaf-50 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 text-leaf-700"/><div><h1 className="font-black">Secure administrator access</h1><p className="mt-1 text-sm text-slate-500">Protected by Supabase Auth, admin roles and route middleware.</p></div></div><label className="mt-6 block"><span className="mb-2 block text-sm font-bold">Admin password</span><span className="relative block"><LockKeyhole className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input required minLength={6} type={show?'text':'password'} autoComplete="current-password" placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)} className="field px-12 py-4"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(x=>!x)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400">{show?<EyeOff className="h-5 w-5"/>:<Eye className="h-5 w-5"/>}</button></span></label>{error&&<p role="alert" className="mt-4 rounded-2xl border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-leaf-700 p-4 font-bold text-white shadow-lg hover:bg-leaf-800 disabled:opacity-50">{busy&&<Loader2 className="h-5 w-5 animate-spin"/>}{busy?'Signing in…':'Open dashboard'}</button><p className="mt-5 text-center text-xs text-slate-400">The configured admin email stays server-side and is never shown in the browser.</p></form></main>;
}
